services:
  python:
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/?sslmode=disable
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/src/
    depends_on:
      db:
        condition: service_healthy
    command: >
      /bin/bash -c "
      psql $$DATABASE_URL < /src/migration.sql && python /src/issue.py
      "
  db:
    image: postgres:14.4
    hostname: db
    command: ["docker-entrypoint.sh", "-c", "log_statement=all"]
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
